// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "OmarFaruk-0x01/sms-trap/app/views/icons"
import "OmarFaruk-0x01/sms-trap/app/views/components/core"

func SmsDetails(activePhone string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col bg-white border-b dark:bg-neutral-800 dark:border-neutral-700 z-50\"><div class=\"p-4 md:p-5 flex justify-between items-start\"><div><div class=\"flex items-center gap-x-2\"><p x-text=\"$store.smsDetails.sms?.phone\" class=\"text-xs uppercase tracking-wide text-gray-500 dark:text-neutral-500\"></p></div><div class=\"mt-1 flex items-center gap-x-2\"><h3 x-text=\"$store.smsDetails.sms?.message\" class=\"text-xl sm:text-lg font-medium text-gray-800 dark:text-neutral-200\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(activePhone)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/components/sms_details.templ`, Line: 15, Col: 19}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h3></div></div><button @click=\"$store.smsDetails.close()\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Close().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></div></div><div class=\"grid grid-cols-2 gap-2 p-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = core.StatsCard(&core.StatsCardProps{
			Title:          "Total Characters",
			ValueAlpineExp: "$store.smsDetails.sms?.characters_count",
			Info:           "Total number of characters",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = core.StatsCard(&core.StatsCardProps{
			Title:          "Total SMS",
			ValueAlpineExp: "$store.smsDetails.sms?.sms_count",
			Info:           "Total number of SMS",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = core.StatsCard(&core.StatsCardProps{
			Title:          "GSM",
			ValueAlpineExp: "$store.smsDetails.sms?.gsm_count",
			Info:           "Total number of GSM characters",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = core.StatsCard(&core.StatsCardProps{
			Title:          "Unicode",
			ValueAlpineExp: "$store.smsDetails.sms?.unicode_count",
			Info:           "Total number of Unicode characters",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"p-2\" x-data=\"{nextRate: 0}\" x-init=\"$watch(&#39;$store.smsDetails.sms?.sms_count&#39;, () =&gt; {\n        nextRate = $store.smsDetails.sms?.type == &#39;Unicode&#39; ? 70 : 160\n    })\"><div class=\"flex flex-col bg-white border shadow-sm rounded-xl dark:bg-neutral-800 dark:border-neutral-700\"><template x-for=\"part in ($store.smsDetails.sms?.sms_count || 0)\"><div class=\"p-3 md:p-3\"><p class=\"text-xs uppercase tracking-wide text-gray-500 dark:text-neutral-500\" x-text=\"`SMS ${part} - ${$store.smsDetails.sms?.type}: ${nextRate}`\"></p><div class=\"flex gap-1 mt-2 flex-wrap text-sm font-light\" x-show=\"$store.smsDetails.open\" style=\"font-family: monospace\"><template x-if=\"$store.smsDetails.sms?.type == &#39;Unicode&#39;\"><template x-for=\"box in 70\"><div class=\"w-5 h-5 text-sm bg-gray-200 rounded-md flex items-center justify-center\" :class=\"{\n                            \t\t&#39;bg-primary-500 text-white&#39;: isASCII($store.smsDetails.sms?.message?.[((part -1) * nextRate) + (box -1)]),\n                            \t\t&#39;bg-red-500 text-white&#39;: isUnicode($store.smsDetails.sms?.message?.[((part -1) * nextRate) + (box -1)])}\" x-text=\"$store.smsDetails.sms?.message?.[((part -1) * nextRate) + (box -1)]\"></div></template></template><template x-if=\"$store.smsDetails.sms?.type == &#39;Text&#39;\"><template x-for=\"box in 160\"><div class=\"w-5 h-5 text-sm bg-gray-200 rounded-md flex items-center justify-center\" :class=\"{\n                            \t\t&#39;bg-primary-500 text-white&#39;: isASCII($store.smsDetails.sms?.message?.[((part -1) * nextRate) + (box -1)]),\n                            \t\t&#39;bg-red-500 text-white&#39;: isUnicode($store.smsDetails.sms?.message?.[((part -1) * nextRate) + (box -1)])}\" x-text=\"$store.smsDetails.sms?.message?.[((part -1) * nextRate) + (box -1)]\"></div></template></template></div></div></template></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
