version: 2

project_name: sms-trap

builds:
  - id: default
    main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: OmarFaruk-0x01
    name: sms-trap
