// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package core

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Tooltip(tooltipText string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-data=\"{\n            tooltipVisible: false,\n            tooltipText: &#39;&#39;,\n            tooltipArrow: true,\n            tooltipPosition: &#39;top&#39;,\n        }\" x-init=\"$refs.content.addEventListener(&#39;mouseenter&#39;, () =&gt; { tooltipVisible = true; }); $refs.content.addEventListener(&#39;mouseleave&#39;, () =&gt; { tooltipVisible = false; });tooltipText = $el.dataset.tooltip\" class=\"relative\" data-tooltip=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(tooltipText)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/components/core/tooltip.templ`, Line: 13, Col: 28}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div x-ref=\"tooltip\" x-show=\"tooltipVisible\" :class=\"{ &#39;top-0 left-1/2 -translate-x-1/2 -mt-0.5 -translate-y-full&#39; : tooltipPosition == &#39;top&#39;, &#39;top-1/2 -translate-y-1/2 -ml-0.5 left-0 -translate-x-full&#39; : tooltipPosition == &#39;left&#39;, &#39;bottom-0 left-1/2 -translate-x-1/2 -mb-0.5 translate-y-full&#39; : tooltipPosition == &#39;bottom&#39;, &#39;top-1/2 -translate-y-1/2 -mr-0.5 right-0 translate-x-full&#39; : tooltipPosition == &#39;right&#39; }\" class=\"absolute w-auto text-sm\" x-cloak><div x-show=\"tooltipVisible\" x-transition class=\"relative px-2 py-1 text-white bg-black rounded bg-opacity-90\"><p x-text=\"tooltipText\" class=\"flex-shrink-0 block text-xs whitespace-nowrap\"></p><div x-ref=\"tooltipArrow\" x-show=\"tooltipArrow\" :class=\"{ &#39;bottom-0 -translate-x-1/2 left-1/2 w-2.5 translate-y-full&#39; : tooltipPosition == &#39;top&#39;, &#39;right-0 -translate-y-1/2 top-1/2 h-2.5 -mt-px translate-x-full&#39; : tooltipPosition == &#39;left&#39;, &#39;top-0 -translate-x-1/2 left-1/2 w-2.5 -translate-y-full&#39; : tooltipPosition == &#39;bottom&#39;, &#39;left-0 -translate-y-1/2 top-1/2 h-2.5 -mt-px -translate-x-full&#39; : tooltipPosition == &#39;right&#39; }\" class=\"absolute inline-flex items-center justify-center overflow-hidden\"><div :class=\"{ &#39;origin-top-left -rotate-45&#39; : tooltipPosition == &#39;top&#39;, &#39;origin-top-left rotate-45&#39; : tooltipPosition == &#39;left&#39;, &#39;origin-bottom-left rotate-45&#39; : tooltipPosition == &#39;bottom&#39;, &#39;origin-top-right -rotate-45&#39; : tooltipPosition == &#39;right&#39; }\" class=\"w-1.5 h-1.5 transform bg-black bg-opacity-90\"></div></div></div></div><div x-ref=\"content\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
