// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ReadyNotification() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ReadyNotification_319a`,
		Function: `function __templ_ReadyNotification_319a(){if (!("Notification" in window)) {
        // Check if the browser supports notifications
        alert("This browser does not support desktop notification");
    } else if (Notification.permission !== "denied") {
        Notification.requestPermission().then((permission) => {
            if (permission === "granted") {
                console.log("Notification permission granted");
            }
        });
    }
}`,
		Call:       templ.SafeScript(`__templ_ReadyNotification_319a`),
		CallInline: templ.SafeScriptInline(`__templ_ReadyNotification_319a`),
	}
}

func ReadyWebSocket() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ReadyWebSocket_78f0`,
		Function: `function __templ_ReadyWebSocket_78f0(){var loc = window.location;
    var uri = 'ws:';

    if (loc.protocol === 'https:') {
      uri = 'wss:';
    }
    uri += '//' + loc.host;
    uri +=  '/ws';

    ws = new WebSocket(uri)

    ws.onopen = function() {
      console.log('Connected')
    }

    ws.onmessage = function(evt) {
        data = JSON.parse(evt.data)
        if (data.trigger_notification) {
            new Notification(` + "`" + `New Sms Recived From ${data?.query?.phones?.join(', ')}` + "`" + `, {
                body: data?.query?.message,
                icon: "https://cdn-icons-png.flaticon.com/512/6711/6711888.png",
                onclick: function() { window.parent.focus();
                         notification.close(); }
            })
        }
    }
}`,
		Call:       templ.SafeScript(`__templ_ReadyWebSocket_78f0`),
		CallInline: templ.SafeScriptInline(`__templ_ReadyWebSocket_78f0`),
	}
}

func RootLayout() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Sms Trap</title><link rel=\"stylesheet\" href=\"/static/css/app.css\"><link rel=\"stylesheet\" defer type=\"text/css\" href=\"/static/css/toastify.min.css\"><script defer type=\"text/javascript\" src=\"/static/js/toastify-js.min.js\"></script><script src=\"/static/js/apexcharts.min.js\"></script><script defer src=\"/static/js/alpinejs.min.js\"></script><style>\n                body {\n                    font-family: 'Exo 2', sans-serif;\n                }\n\n                [x-cloak] {\n                    display: none;\n                }\n            </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ReadyNotification().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ReadyWebSocket().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</head><body class=\"exo-2-regular\"><header class=\"px-5 py-2 flex items-center justify-between\"><img src=\"/static/logo.svg\" alt=\"logo\" width=\"200px\" height=\"0px\"></header><hr>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
